''
  ### Examples

  Creating JSON, TEXT, TOML or YAML files

  ```nix
  ${builtins.readFile ../hello.nix}
  ```

  Your file can be complemented with another module

  ```nix
  ${builtins.readFile ../world.nix}
  ```

  Content generated by those examples are in [generated](./generated/)

  ```YAML
  # ie ./generated/hello.yaml
  ${builtins.readFile ../../generated/hello.yaml}
  ```

  ### Dogfooding

  This project is configured by module [project.nix](./project.nix)

  ```nix
  # ./project.nix
  ${builtins.readFile ../../project.nix}
  ```

  This README.md is also a module defined as above

  ```nix
  ${builtins.readFile ../readme.nix}
  ```

  Our .gitignore is defined like this
  ```nix
  # ./examples/gitignore.nix
  ${builtins.readFile ../gitignore.nix}
  ```

  And our LICENSE file is
  ```nix
  # ./examples/license.nix
  ${builtins.readFile ../license.nix}
  ```
''
