''
  ## Install Examples
  
  <!-- this is also a example o string interpolation -->
  ```nix
  ${builtins.readFile ../../flake.nix}
  ```

  ## Module Examples

  Creating JSON, TEXT, TOML or YAML files

  ```nix
  ${builtins.readFile ../hello.nix}
  ```

  Your file can be complemented with another file

  ```nix
  ${builtins.readFile ../world.nix}
  ```

  Content generated by those examples

  ```JSON
  ${builtins.readFile ../../generated/hello.json}
  ```

  ```text
  ${builtins.readFile ../../generated/hello.txt}
  ```

  ```TOML
  ${builtins.readFile ../../generated/hello.toml}
  ```

  ```YAML
  ${builtins.readFile ../../generated/hello.yaml}
  ```
''
